export const MATCHES_LIST_REQUEST = "MATCHES_LIST_REQUEST";
export const MATCHES_LIST_SUCCESS = "MATCHES_LIST_SUCCESS";
export const MATCHES_LIST_FAIL = "MATCHES_LIST_FAIL";
export const MATCHES_CREATE_REQUEST = "MATCH_CREATE_REQUEST";
export const MATCHES_CREATE_SUCCESS = "MATCH_CREATE_SUCCESS";
export const MATCHES_CREATE_FAIL = "MATCH_CREATE_FAIL";
